package com.philipgreen.dmwizard.races.utils;

/**
 * Created by pgreen on 11/1/16.
 */

public enum SubRaceListEnum {
    HILL_DWARF, MOUNTAIN_DWARF,
    HIGH_ELF, DARK_ELF, WOOD_ELF,
    FOREST_GNOME, ROCK_GNOME,
    BLACK_DRAGONBORN, BLUE_DRAGONBORN, BRASS_DRAGONBORN, BRONZE_DRAGONBORN, COPPER_DRAGONBORN,
    GOLD_DRAGONBORN, GREEN_DRAGONBORN, RED_DRAGONBORN, SILVER_DRAGONBORN, WHITE_DRAGONBORN,
}
