package com.philipgreen.dmwizard.player.utils;

/**
 * Created by pgreen on 8/6/16.
 */
public enum Skills {
    ACROBATICS, ANIMAL_HANDLING, ARCANA, ATHLETICS, DECEPTION, HISTORY, INSIGHT,
    INTIMIDATION, INVESTIGATION, MEDICINE, NATURE, PERCEPTION, PERFORMANCE, PERSUASION,
    RELIGION, SLEIGHT_OF_HAND, STEALTH, SURVIVAL
}
